# Generated by Django 3.2.20 on 2023-07-21 12:22

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLevelMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyu_level', models.CharField(max_length=10, verbose_name='Kyu Level')),
                ('belt_color', models.CharField(max_length=50, verbose_name='Karate Belt Color')),
                ('kata_name', models.CharField(max_length=50, verbose_name='Kata Name')),
                ('kata_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('syllabus_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
            options={
                'ordering': ['-kyu_level'],
            },
        ),
        migrations.CreateModel(
            name='StudentInfoMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('address_1', models.CharField(max_length=50, verbose_name='Address Line One')),
                ('address_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address Line Two')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('post_code', models.CharField(max_length=10, verbose_name='Post Code')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('student_grade', models.ForeignKey(default=9, on_delete=django.db.models.deletion.DO_NOTHING, to='shotokanapp.studentlevelmod', verbose_name='Student Grade')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
