# Generated by Django 3.2.20 on 2023-07-30 21:15

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shotokanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('description', models.CharField(max_length=100)),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterField(
            model_name='studentinfomod',
            name='student_grade',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='shotokanapp.studentlevelmod', verbose_name='Student Grade'),
        ),
    ]
