# Generated by Django 3.2.20 on 2023-08-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shotokanapp', '0002_auto_20230730_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentsGroup',
        ),
    ]
