# Generated by Django 3.2.20 on 2023-08-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shotokanapp', '0004_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
