# Generated by Django 3.2.20 on 2023-08-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shotokanapp', '0005_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlevelmod',
            name='kyu_level',
            field=models.CharField(max_length=15, verbose_name='Kyu Level'),
        ),
    ]
