# Generated by Django 3.2.20 on 2023-08-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shotokanapp', '0006_alter_customuser_student_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentlevelmod',
            options={'ordering': ['-kyu_level'], 'verbose_name': 'Kyu Level', 'verbose_name_plural': 'Kyu Levels'},
        ),
    ]
