# Generated by Django 3.2.20 on 2023-08-16 21:14

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shotokanapp', '0008_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenseiMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Sensei Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Sensei Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Sensei Email Address')),
                ('contact_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Sensei Mobile')),
            ],
            options={
                'verbose_name': 'Sensei',
                'verbose_name_plural': 'Sensei',
                'ordering': ['-first_name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='sensei',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='shotokanapp.senseimod', verbose_name='Sensei'),
        ),
    ]
