# Generated by Django 3.2.20 on 2023-08-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shotokanapp', '0009_auto_20230816_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='senseimod',
            options={'ordering': ['-sensei_first_name'], 'verbose_name': 'Sensei', 'verbose_name_plural': 'Sensei'},
        ),
        migrations.RenameField(
            model_name='senseimod',
            old_name='contact_num',
            new_name='sensei_contact_num',
        ),
        migrations.RenameField(
            model_name='senseimod',
            old_name='email',
            new_name='sensei_email',
        ),
        migrations.RenameField(
            model_name='senseimod',
            old_name='first_name',
            new_name='sensei_first_name',
        ),
        migrations.RenameField(
            model_name='senseimod',
            old_name='last_name',
            new_name='sensei_last_name',
        ),
    ]
