# Generated by Django 3.2.20 on 2023-08-21 13:56

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shotokanapp', '0012_alter_customuser_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Student Contact'),
        ),
    ]
