# Generated by Django 3.2.20 on 2023-09-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shotokanapp', '0014_alter_customuser_contact_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Shotokan Members', 'verbose_name_plural': 'Shotokan Members'},
        ),
    ]
