# Generated by Django 3.2.20 on 2023-09-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shotokanapp', '0019_auto_20230901_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Student Contact', 'verbose_name_plural': 'Student Contact'},
        ),
    ]
