# Generated by Django 3.2.20 on 2023-09-01 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shotokanapp', '0020_alter_contact_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
